CREATE TYPE event_status AS ENUM ('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED');
CREATE TYPE ticket_tier AS ENUM ('GENERAL', 'FLOOR', 'VIP');
CREATE TYPE ticket_status AS ENUM ('VALID', 'USED', 'CANCELLED');
CREATE TYPE order_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED');
CREATE TYPE payment_status AS ENUM ('SUCCESS', 'FAILED');
CREATE TYPE payment_method AS ENUM ('MOCK');
CREATE TYPE user_role AS ENUM ('CUSTOMER', 'ADMIN');